name: note_flow
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  sqflite: ^2.3.3+1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  path: ^1.9.0
  staggered_grid_view_flutter: ^0.0.4
  flutter_colorpicker: ^1.1.0
  get_it: ^7.7.0
  injectable: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1
  mocktail: ^1.0.3
  bloc_test: ^9.1.7


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_foreground.png"


flutter:

  
  uses-material-design: true

  assets:
    - assets/
